/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "zxyvqsevekrhwzjulyaq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4eXZxc2V2ZWtyaHd6anVseWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NTMzNDgsImV4cCI6MjA2ODIyOTM0OH0.1uG9-dGGkuiFFWz0zxtjN54dPjMxbSWjii0n9SC-KgY"